services:
  backend:
    build: ./back2
    ports:
      - "8000:8000"
    environment:
      - IA_API_URL=http://back-ia:5000/api/v1/analyzer
    volumes:
      - ./back2/src/main/resources/firebase-service-account.json:/app/resources/firebase-service-account.json
    depends_on:
      - back-ia

  back-ia:
    build: ./back_IA
    ports:
      - "5000:5000"
    env_file:
      - ./back_IA/.env
    restart: always

  frontend:
    build: ./front2
    ports:
      - "4200:4200"
    depends_on:
      - backend
